default: &default
  adapter: sqlite3
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qa_platform_development
  username: sloboda
  password: 'sloboda123'

test:
  <<: *default
  database: qa_platform_test

production:
  <<: *default
  database: qa_platform_production
  username: qa_platform
  password: <%= ENV['RM-CORE_DATABASE_PASSWORD'] %>

